export interface MeasurementGuideItem {
  key: string;
  label: string;
  category: 'UPPER_BODY' | 'ARMS' | 'LOWER_BODY' | 'LENGTH' | 'GENERAL' | 'ACCESSORIES';
  categoryLabel: string;
  summary: string;
  howToMeasure: string[];
  proTip: string;
  commonMistake: string;
  minCm: number;
  maxCm: number;
  minInches: number;
  maxInches: number;
  silhouetteRegion: 'torso' | 'arms' | 'legs' | 'lengths' | 'head';
  indicatorY: number; // Percentage 0-100 for SVG marker position
  indicatorType: 'circumference' | 'vertical' | 'horizontal' | 'curve';
}

export const MEASUREMENT_GUIDES: MeasurementGuideItem[] = [
  // ── General ─────────────────────────────────────────────────────────────
  {
    key: 'HEIGHT',
    label: 'Height',
    category: 'GENERAL',
    categoryLabel: 'General Dimensions',
    summary: 'Total vertical height from the crown of the head straight down to the floor, standing upright against a wall without shoes.',
    howToMeasure: [
      'Stand barefoot or in thin socks with your heels, back, and head flat against a vertical wall.',
      'Keep your posture straight and look directly forward.',
      'Place a flat object (like a book or ruler) level across the top of your head and mark the wall.',
      'Measure straight down from the wall mark to the floor.',
    ],
    proTip: 'Do not measure down along the front curve of your body or while wearing shoes or standing on plush carpet.',
    commonMistake: 'Measuring diagonally or down along body curves to the toes instead of a straight vertical drop to the floor.',
    minCm: 120,
    maxCm: 230,
    minInches: 47,
    maxInches: 90,
    silhouetteRegion: 'lengths',
    indicatorY: 50,
    indicatorType: 'vertical',
  },

  // ── Upper Body ──────────────────────────────────────────────────────────
  {
    key: 'NECK',
    label: 'Neck Circumference',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Circumference around the base of the neck where a buttoned shirt collar rests.',
    howToMeasure: [
      'Position the measuring tape around the base of your neck, just below the Adam’s apple (thyroid cartilage).',
      'Keep the tape flat against the skin without digging in.',
      'Insert two fingers flat between the tape and your neck to ensure a comfortable breathing ease allowance.',
    ],
    proTip: 'For dress shirts, add 1.25 cm (0.5 in) to your exact skin measurement for collar comfort.',
    commonMistake: 'Measuring too high on the throat instead of where the collar sits at the base.',
    minCm: 25,
    maxCm: 60,
    minInches: 10,
    maxInches: 24,
    silhouetteRegion: 'torso',
    indicatorY: 12,
    indicatorType: 'circumference',
  },
  {
    key: 'SHOULDER_WIDTH',
    label: 'Shoulder Width (Across Back)',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Distance across the upper back from the tip of one shoulder bone to the other.',
    howToMeasure: [
      'Locate the bony point (acromion process) at the top edge of your left shoulder.',
      'Follow the natural curve of your upper back across the base of the neck to the bony point on your right shoulder.',
      'Keep your shoulders relaxed in their natural resting posture.',
    ],
    proTip: 'Have a friend take this measurement; measuring your own back shoulders causes arm elevation that distorts width.',
    commonMistake: 'Pulling shoulders back or slouching during measurement.',
    minCm: 25,
    maxCm: 65,
    minInches: 10,
    maxInches: 26,
    silhouetteRegion: 'torso',
    indicatorY: 18,
    indicatorType: 'horizontal',
  },
  {
    key: 'ACROSS_FRONT',
    label: 'Across Front Chest',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Horizontal width across the upper chest from armhole crease to armhole crease.',
    howToMeasure: [
      'Locate the front armpit crease where your arm joins your torso on both sides.',
      'Measure horizontally across the upper chest between these two points, roughly 7-10 cm below the hollow of your neck.',
      'Keep your arms resting naturally at your sides.',
    ],
    proTip: 'Essential for jacket chest drape and preventing front armhole gaping.',
    commonMistake: 'Measuring over thick padded jackets or lifting elbows.',
    minCm: 22,
    maxCm: 60,
    minInches: 9,
    maxInches: 24,
    silhouetteRegion: 'torso',
    indicatorY: 22,
    indicatorType: 'horizontal',
  },
  {
    key: 'ACROSS_BACK',
    label: 'Across Back',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Horizontal width across the back between the back armhole folds.',
    howToMeasure: [
      'Locate the back armhole creases where arms connect to the torso.',
      'Measure straight across the shoulder blade level from crease to crease.',
      'Keep arms hanging loose and relaxed.',
    ],
    proTip: 'Determines whether a fitted suit or blazer will feel constricting when driving or typing.',
    commonMistake: 'Tensing back muscles or flexing shoulder blades.',
    minCm: 25,
    maxCm: 62,
    minInches: 10,
    maxInches: 24.5,
    silhouetteRegion: 'torso',
    indicatorY: 23,
    indicatorType: 'horizontal',
  },
  {
    key: 'CHEST_BUST',
    label: 'Full Chest / Bust',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Fullest circumference around the chest or bust, keeping the tape level parallel to the floor.',
    howToMeasure: [
      'Wrap the measuring tape around the fullest part of your chest/bust (across the apex/nipples).',
      'Ensure the tape is completely level across your back shoulder blades and under your armpits.',
      'Breathe normally and keep arms relaxed down at your sides.',
    ],
    proTip: 'Wear the foundation bra or undergarments you intend to wear with the finished garment.',
    commonMistake: 'Letting the tape droop down the back, causing an undersized reading.',
    minCm: 50,
    maxCm: 180,
    minInches: 20,
    maxInches: 71,
    silhouetteRegion: 'torso',
    indicatorY: 28,
    indicatorType: 'circumference',
  },
  {
    key: 'HIGH_BUST',
    label: 'High Bust',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Circumference taken above the bust apex, straight through the upper armpits.',
    howToMeasure: [
      'Pass the tape directly under your armpits and across the upper chest above the breast tissue.',
      'Keep the tape snug and parallel to the floor.',
    ],
    proTip: 'Crucial for pattern makers to calculate cup size (Full Bust minus High Bust = cup size calculation).',
    commonMistake: 'Slipping onto breast tissue rather than sitting directly above it.',
    minCm: 50,
    maxCm: 170,
    minInches: 20,
    maxInches: 67,
    silhouetteRegion: 'torso',
    indicatorY: 24,
    indicatorType: 'circumference',
  },
  {
    key: 'UNDERBUST',
    label: 'Underbust (Ribcage Band)',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Circumference directly below the breast fold, where a bra band or empire waist sits.',
    howToMeasure: [
      'Position the tape directly under the bust line firmly around the ribcage.',
      'Exhale normally and keep tape snug against the body.',
    ],
    proTip: 'Used for corsetry, bralettes, empire-waist dresses, and swimwear.',
    commonMistake: 'Inhaling deeply and holding breath during measurement.',
    minCm: 45,
    maxCm: 160,
    minInches: 18,
    maxInches: 63,
    silhouetteRegion: 'torso',
    indicatorY: 34,
    indicatorType: 'circumference',
  },
  {
    key: 'BUST_POINT_TO_BUST_POINT',
    label: 'Bust Point to Bust Point (Apex Distance)',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Horizontal distance between the two bust apex (nipple) points.',
    howToMeasure: [
      'Wearing a well-fitting standard bra, measure horizontally from the apex of one bust to the other.',
    ],
    proTip: 'Governs dart placement and princess seam positioning for bespoke dresses and tops.',
    commonMistake: 'Measuring along a sagged curve rather than a straight horizontal bridge.',
    minCm: 10,
    maxCm: 35,
    minInches: 4,
    maxInches: 14,
    silhouetteRegion: 'torso',
    indicatorY: 29,
    indicatorType: 'horizontal',
  },
  {
    key: 'BUST_APEX_HEIGHT',
    label: 'Bust Apex Height',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Vertical distance from the shoulder-neck junction straight down to the bust apex.',
    howToMeasure: [
      'Start where the neck meets the shoulder line.',
      'Run the tape straight down over the chest to the prominent apex of the bust.',
    ],
    proTip: 'Ensures darts point directly at the apex rather than above or below.',
    commonMistake: 'Starting from the outer shoulder joint rather than the base of the neck.',
    minCm: 15,
    maxCm: 45,
    minInches: 6,
    maxInches: 18,
    silhouetteRegion: 'torso',
    indicatorY: 25,
    indicatorType: 'vertical',
  },
  {
    key: 'WAIST',
    label: 'Natural Waist',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Circumference at the narrowest point of the torso, above the belly button and below the ribcage.',
    howToMeasure: [
      'Bend side to side to locate your natural waist crease.',
      'Wrap tape around this narrowest point, keeping it level and flat against skin.',
      'Place one finger under the tape for breathing ease.',
    ],
    proTip: 'Do not suck in your stomach; stand naturally with regular breathing.',
    commonMistake: 'Measuring at trousers waistband (trouser waist is typically 5-8 cm lower than natural waist).',
    minCm: 40,
    maxCm: 180,
    minInches: 16,
    maxInches: 71,
    silhouetteRegion: 'torso',
    indicatorY: 42,
    indicatorType: 'circumference',
  },
  {
    key: 'STOMACH',
    label: 'Stomach / Widest Abdomen',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Circumference around the fullest projection of the belly / lower abdomen.',
    howToMeasure: [
      'Wrap tape around the fullest part of your abdomen (usually 3-5 cm below natural waist, over the belly button).',
      'Keep tape horizontal and level.',
    ],
    proTip: 'Essential for fitted trousers, pencil skirts, and tailored waistcoats.',
    commonMistake: 'Squeezing the tape into soft tissue.',
    minCm: 45,
    maxCm: 190,
    minInches: 18,
    maxInches: 75,
    silhouetteRegion: 'torso',
    indicatorY: 47,
    indicatorType: 'circumference',
  },
  {
    key: 'UPPER_HIP',
    label: 'Upper Hip (High Hip)',
    category: 'UPPER_BODY',
    categoryLabel: 'Upper Body & Torso',
    summary: 'Circumference around the pelvic bone crest, roughly 8 cm below the natural waistline.',
    howToMeasure: [
      'Feel for the top bony ridge of your hip bones (iliac crest).',
      'Wrap tape level around this high hip point.',
    ],
    proTip: 'Determines the waistband fit of mid-rise jeans and A-line skirts.',
    commonMistake: 'Confusing high hip with the widest hip/seat measurement.',
    minCm: 50,
    maxCm: 190,
    minInches: 20,
    maxInches: 75,
    silhouetteRegion: 'torso',
    indicatorY: 52,
    indicatorType: 'circumference',
  },

  // ── Arms ────────────────────────────────────────────────────────────────
  {
    key: 'ARMHOLE',
    label: 'Armhole (Armscye)',
    category: 'ARMS',
    categoryLabel: 'Arms & Sleeves',
    summary: 'Circumference of the armhole through the armpit and over the top shoulder bone.',
    howToMeasure: [
      'Pass the tape under the armpit and loop over the top tip of the shoulder bone.',
      'Tape should be comfortable without cutting into the underarm crease.',
    ],
    proTip: 'Move your arm back and forth while checking to ensure armhole mobility.',
    commonMistake: 'Pulling too tight into the armpit socket.',
    minCm: 25,
    maxCm: 70,
    minInches: 10,
    maxInches: 27.5,
    silhouetteRegion: 'arms',
    indicatorY: 22,
    indicatorType: 'circumference',
  },
  {
    key: 'ARMHOLE_DEPTH',
    label: 'Armhole Depth',
    category: 'ARMS',
    categoryLabel: 'Arms & Sleeves',
    summary: 'Vertical drop from the top shoulder point straight down to the base level of the armpit.',
    howToMeasure: [
      'Place a ruler gently horizontally under your armpit.',
      'Measure vertically from the shoulder seam down to the ruler line.',
    ],
    proTip: 'Governs sleeve crown drafting and jacket comfort.',
    commonMistake: 'Angling the tape diagonally rather than plumb vertical.',
    minCm: 10,
    maxCm: 35,
    minInches: 4,
    maxInches: 14,
    silhouetteRegion: 'arms',
    indicatorY: 24,
    indicatorType: 'vertical',
  },
  {
    key: 'BICEP',
    label: 'Bicep (Upper Arm)',
    category: 'ARMS',
    categoryLabel: 'Arms & Sleeves',
    summary: 'Circumference around the fullest part of your upper arm (bicep).',
    howToMeasure: [
      'Let arm hang naturally with a very slight elbow bend.',
      'Measure around the thickest portion of the upper arm between shoulder and elbow.',
    ],
    proTip: 'Measure both arms and use the larger measurement if right/left handed asymmetry exists.',
    commonMistake: 'Flexing the bicep during measurement unless specifically requested by tailor.',
    minCm: 15,
    maxCm: 60,
    minInches: 6,
    maxInches: 24,
    silhouetteRegion: 'arms',
    indicatorY: 28,
    indicatorType: 'circumference',
  },
  {
    key: 'ELBOW',
    label: 'Elbow Circumference',
    category: 'ARMS',
    categoryLabel: 'Arms & Sleeves',
    summary: 'Circumference around the elbow joint with the arm bent at 90 degrees.',
    howToMeasure: [
      'Bend your arm at a 90-degree right angle.',
      'Wrap tape directly over the point of the elbow and inner crease.',
    ],
    proTip: 'Bending the arm ensures slim sleeves and jacket elbows do not bind when bending your arm.',
    commonMistake: 'Measuring with a straight arm, which produces a sleeve that binds when bending.',
    minCm: 15,
    maxCm: 50,
    minInches: 6,
    maxInches: 20,
    silhouetteRegion: 'arms',
    indicatorY: 38,
    indicatorType: 'circumference',
  },
  {
    key: 'WRIST',
    label: 'Wrist Circumference',
    category: 'ARMS',
    categoryLabel: 'Arms & Sleeves',
    summary: 'Circumference around the wrist bone where a shirt cuff closes.',
    howToMeasure: [
      'Wrap tape around the wrist just over the prominent wrist bone.',
      'Add 2-3 cm (1 inch) ease for standard shirt cuffs and watch clearance.',
    ],
    proTip: 'If you wear a thick wristwatch on one wrist, measure that wrist for tailored shirts.',
    commonMistake: 'Measuring too high up the forearm.',
    minCm: 10,
    maxCm: 30,
    minInches: 4,
    maxInches: 12,
    silhouetteRegion: 'arms',
    indicatorY: 48,
    indicatorType: 'circumference',
  },
  {
    key: 'SLEEVE_LENGTH_LONG',
    label: 'Long Sleeve Length',
    category: 'ARMS',
    categoryLabel: 'Arms & Sleeves',
    summary: 'Distance from the shoulder point along the outer arm over the elbow down to the wrist bone.',
    howToMeasure: [
      'Bend arm slightly with hand on hip.',
      'Start from the shoulder bone point, pass over the elbow point, and end at the wrist bone.',
    ],
    proTip: 'The slight bend is crucial: a sleeve measured on a straight arm will pull up above the wrist when you reach forward.',
    commonMistake: 'Measuring straight down without including the elbow curve.',
    minCm: 30,
    maxCm: 80,
    minInches: 12,
    maxInches: 31.5,
    silhouetteRegion: 'arms',
    indicatorY: 35,
    indicatorType: 'vertical',
  },
  {
    key: 'SLEEVE_LENGTH_SHORT',
    label: 'Short Sleeve Length',
    category: 'ARMS',
    categoryLabel: 'Arms & Sleeves',
    summary: 'Distance from the shoulder point down to your desired short sleeve hem.',
    howToMeasure: [
      'Measure straight down the outer arm from the shoulder bone to mid-bicep (or desired hem length).',
    ],
    proTip: 'Standard short sleeve hems sit approximately 10-15 cm below the shoulder seam.',
    commonMistake: 'Starting from the collar rather than the shoulder tip.',
    minCm: 8,
    maxCm: 45,
    minInches: 3,
    maxInches: 18,
    silhouetteRegion: 'arms',
    indicatorY: 26,
    indicatorType: 'vertical',
  },
  {
    key: 'SLEEVE_OPENING',
    label: 'Sleeve Opening (Cuff Hem)',
    category: 'ARMS',
    categoryLabel: 'Arms & Sleeves',
    summary: 'Circumference around the finished edge of the sleeve cuff/opening.',
    howToMeasure: [
      'Wrap tape around the arm at the exact position where the sleeve hem will terminate.',
    ],
    proTip: 'For non-stretch fabrics, ensure the opening is large enough for hands to slide through.',
    commonMistake: 'Making sleeve openings too tight for hand passage.',
    minCm: 10,
    maxCm: 50,
    minInches: 4,
    maxInches: 20,
    silhouetteRegion: 'arms',
    indicatorY: 48,
    indicatorType: 'circumference',
  },

  // ── Lower Body ──────────────────────────────────────────────────────────
  {
    key: 'HIP_SEAT',
    label: 'Hips / Full Seat',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Circumference around the widest, fullest part of the buttocks and hips.',
    howToMeasure: [
      'Stand with heels together and weight evenly distributed.',
      'Wrap tape around the fullest projection of your buttocks (typically 18-23 cm below natural waist).',
      'Ensure tape is strictly parallel to the floor all the way around.',
    ],
    proTip: 'Use a mirror to verify that the tape has not slipped down in the back.',
    commonMistake: 'Measuring too high (over the hip bones) rather than the fullest projection of the seat.',
    minCm: 50,
    maxCm: 200,
    minInches: 20,
    maxInches: 79,
    silhouetteRegion: 'legs',
    indicatorY: 56,
    indicatorType: 'circumference',
  },
  {
    key: 'THIGH',
    label: 'Thigh Circumference',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Circumference around the fullest part of the upper thigh, just below the crotch.',
    howToMeasure: [
      'Stand with feet shoulder-width apart.',
      'Wrap tape around the widest part of the thigh, 2-3 cm below the crotch line.',
    ],
    proTip: 'Measure both thighs; dominant leg is often slightly larger.',
    commonMistake: 'Tensing the quad muscle or measuring while seated.',
    minCm: 25,
    maxCm: 100,
    minInches: 10,
    maxInches: 39,
    silhouetteRegion: 'legs',
    indicatorY: 64,
    indicatorType: 'circumference',
  },
  {
    key: 'KNEE',
    label: 'Knee Circumference',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Circumference around the knee joint with leg straight or slightly relaxed.',
    howToMeasure: [
      'Wrap tape around the middle of the kneecap (patella) with weight on that leg.',
    ],
    proTip: 'Essential for tailored trousers, skinny jeans, and knee-high boots.',
    commonMistake: 'Bending knee excessively unless measuring for athletic tights.',
    minCm: 20,
    maxCm: 70,
    minInches: 8,
    maxInches: 28,
    silhouetteRegion: 'legs',
    indicatorY: 74,
    indicatorType: 'circumference',
  },
  {
    key: 'CALF',
    label: 'Calf Circumference',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Circumference around the widest part of the lower leg muscle.',
    howToMeasure: [
      'Stand flat-footed and wrap tape around the thickest bulge of the calf muscle.',
    ],
    proTip: 'Crucial for tapered trousers and boots.',
    commonMistake: 'Standing on tiptoes during measurement.',
    minCm: 18,
    maxCm: 70,
    minInches: 7,
    maxInches: 28,
    silhouetteRegion: 'legs',
    indicatorY: 82,
    indicatorType: 'circumference',
  },
  {
    key: 'ANKLE',
    label: 'Ankle Circumference',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Circumference around the narrowest part of the lower leg just above the ankle bone.',
    howToMeasure: [
      'Wrap tape horizontally around the leg just above the protruding malleolus (ankle bone).',
    ],
    proTip: 'Controls trouser leg opening taper and cuff break.',
    commonMistake: 'Measuring over socks or shoe collars.',
    minCm: 15,
    maxCm: 45,
    minInches: 6,
    maxInches: 18,
    silhouetteRegion: 'legs',
    indicatorY: 90,
    indicatorType: 'circumference',
  },
  {
    key: 'CROTCH_RISE',
    label: 'Total Crotch / Rise',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Total distance from front waistband, through the legs, to the back waistband.',
    howToMeasure: [
      'Anchor tape at the center-front natural waistband position.',
      'Pass tape between legs and pull up to the center-back waistband position.',
      'Allow comfortable ease without pulling tight against the groin.',
    ],
    proTip: 'Wear the style of underwear you normally wear with trousers.',
    commonMistake: 'Pulling the tape too taut into the body.',
    minCm: 40,
    maxCm: 110,
    minInches: 16,
    maxInches: 43,
    silhouetteRegion: 'legs',
    indicatorY: 60,
    indicatorType: 'vertical',
  },
  {
    key: 'INSEAM',
    label: 'Inseam (Inside Leg)',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Distance along the inner leg from the crotch point down to the ankle / bottom trouser hem.',
    howToMeasure: [
      'Stand straight with feet 15 cm apart, heels against a wall.',
      'Anchor tape at the highest inner thigh/crotch junction.',
      'Measure straight down the inside of the leg to the bottom of the ankle bone (or shoe top).',
    ],
    proTip: 'You can also measure the inside seam of a pair of trousers that fits you perfectly.',
    commonMistake: 'Bending down to read the tape (have a friend measure or step on the tape).',
    minCm: 40,
    maxCm: 110,
    minInches: 16,
    maxInches: 43,
    silhouetteRegion: 'legs',
    indicatorY: 76,
    indicatorType: 'vertical',
  },
  {
    key: 'OUTSEAM',
    label: 'Outseam (Trouser Length)',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Distance along the outside of the leg from the natural waistband down to the desired trouser hem.',
    howToMeasure: [
      'Stand straight and measure down the outside seam from the natural waistband over the hip bone to the floor/shoe hem.',
    ],
    proTip: 'Decide whether you want a full break, half break, or no break at the shoe.',
    commonMistake: 'Measuring with bent knees.',
    minCm: 60,
    maxCm: 140,
    minInches: 24,
    maxInches: 55,
    silhouetteRegion: 'legs',
    indicatorY: 72,
    indicatorType: 'vertical',
  },
  {
    key: 'WAIST_TO_HIP',
    label: 'Waist to Hip Length',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Vertical distance down the side from the natural waist to the fullest hip line.',
    howToMeasure: [
      'Measure vertically down the outer hip from the natural waist crease to the fullest part of the seat.',
    ],
    proTip: 'Usually 18-20 cm (7-8 in) for standard women’s patterns, 20-23 cm for men’s.',
    commonMistake: 'Measuring along the curvy surface rather than a straight vertical drop.',
    minCm: 10,
    maxCm: 40,
    minInches: 4,
    maxInches: 16,
    silhouetteRegion: 'legs',
    indicatorY: 50,
    indicatorType: 'vertical',
  },
  {
    key: 'WAIST_TO_KNEE',
    label: 'Waist to Knee Length',
    category: 'LOWER_BODY',
    categoryLabel: 'Lower Body & Legs',
    summary: 'Vertical distance down the side from the natural waist to the midpoint of the knee.',
    howToMeasure: [
      'Measure straight down the outer side of the leg from natural waist to the knee joint center.',
    ],
    proTip: 'Key landmark for skirt lengths and Bermuda shorts.',
    commonMistake: 'Bending the knee during measurement.',
    minCm: 35,
    maxCm: 85,
    minInches: 14,
    maxInches: 33.5,
    silhouetteRegion: 'legs',
    indicatorY: 65,
    indicatorType: 'vertical',
  },

  // ── Lengths ─────────────────────────────────────────────────────────────
  {
    key: 'NAPE_TO_WAIST',
    label: 'Nape to Waist (Center Back Length)',
    category: 'LENGTH',
    categoryLabel: 'Garment Lengths',
    summary: 'Distance down the center spine from the prominent base neck bone (C7 vertebra) to the natural waist.',
    howToMeasure: [
      'Tilt head forward to feel the prominent bone at the base of your neck (C7 vertebrae).',
      'Measure straight down the center spine to the natural waistline level.',
    ],
    proTip: 'Fundamental for jacket and dress torso balance (stops dresses from riding up or bagging at the lower back).',
    commonMistake: 'Starting too high on the neck.',
    minCm: 25,
    maxCm: 60,
    minInches: 10,
    maxInches: 24,
    silhouetteRegion: 'lengths',
    indicatorY: 30,
    indicatorType: 'vertical',
  },
  {
    key: 'FRONT_LENGTH_SHOULDER_TO_WAIST',
    label: 'Front Shoulder to Waist Length',
    category: 'LENGTH',
    categoryLabel: 'Garment Lengths',
    summary: 'Distance from the shoulder-neck point over the bust apex down to the natural waist.',
    howToMeasure: [
      'Start at the highest point of the shoulder at the base of the neck.',
      'Pass tape over the bust apex and straight down to the natural waistline.',
    ],
    proTip: 'Crucial for bodice drafting: front length is usually longer than back length due to bust curve.',
    commonMistake: 'Taking a diagonal line that bypasses the bust apex.',
    minCm: 25,
    maxCm: 60,
    minInches: 10,
    maxInches: 24,
    silhouetteRegion: 'lengths',
    indicatorY: 32,
    indicatorType: 'vertical',
  },
  {
    key: 'TOP_LENGTH',
    label: 'Shirt / Top Length',
    category: 'LENGTH',
    categoryLabel: 'Garment Lengths',
    summary: 'Distance from the shoulder-neck point down to your desired top/shirt hem.',
    howToMeasure: [
      'Measure from the neck-shoulder base down the front to where you want the shirt hem to end (e.g. mid-hip).',
    ],
    proTip: 'If you plan to tuck in the shirt, add 8-10 cm so it stays tucked when sitting.',
    commonMistake: 'Measuring from the collar center rather than the shoulder seam.',
    minCm: 35,
    maxCm: 110,
    minInches: 14,
    maxInches: 43,
    silhouetteRegion: 'lengths',
    indicatorY: 45,
    indicatorType: 'vertical',
  },
  {
    key: 'DRESS_LENGTH',
    label: 'Dress Length (Total Length)',
    category: 'LENGTH',
    categoryLabel: 'Garment Lengths',
    summary: 'Distance from the shoulder point down to the desired dress hemline (mini, midi, maxi).',
    howToMeasure: [
      'Start at the highest shoulder point next to the neck.',
      'Run tape over the bust and straight down to the desired hem (above knee, mid-calf, or floor).',
    ],
    proTip: 'Wear the shoes/heels you intend to wear with the dress when measuring maxi dresses.',
    commonMistake: 'Looking down while measuring, which pulls the tape up by several centimeters.',
    minCm: 60,
    maxCm: 180,
    minInches: 24,
    maxInches: 71,
    silhouetteRegion: 'lengths',
    indicatorY: 60,
    indicatorType: 'vertical',
  },
  {
    key: 'SKIRT_LENGTH',
    label: 'Skirt Length',
    category: 'LENGTH',
    categoryLabel: 'Garment Lengths',
    summary: 'Distance from the natural waist down the center front to the desired skirt hem.',
    howToMeasure: [
      'Anchor tape at the natural waistline.',
      'Measure straight down the front of the body to the desired skirt hemline.',
    ],
    proTip: 'For high-waisted skirts, start measuring at the high waistline position.',
    commonMistake: 'Measuring from low hips instead of intended waistband placement.',
    minCm: 20,
    maxCm: 130,
    minInches: 8,
    maxInches: 51,
    silhouetteRegion: 'lengths',
    indicatorY: 62,
    indicatorType: 'vertical',
  },
  {
    key: 'JACKET_LENGTH',
    label: 'Suit / Jacket Length',
    category: 'LENGTH',
    categoryLabel: 'Garment Lengths',
    summary: 'Distance down the center back from the collar base seam to the jacket bottom hem.',
    howToMeasure: [
      'Start at the base of the collar at the center back.',
      'Measure straight down the spine to where the jacket should end (traditionally covering the seat curve).',
    ],
    proTip: 'A classic suit jacket hem should divide the total body height from collar to floor roughly in half.',
    commonMistake: 'Making jackets too short so they expose the shirt or seat.',
    minCm: 40,
    maxCm: 130,
    minInches: 16,
    maxInches: 51,
    silhouetteRegion: 'lengths',
    indicatorY: 48,
    indicatorType: 'vertical',
  },

  // ── Accessories ─────────────────────────────────────────────────────────
  {
    key: 'HEAD_CIRCUMFERENCE',
    label: 'Head Circumference',
    category: 'ACCESSORIES',
    categoryLabel: 'Head & Accessories',
    summary: 'Circumference around the widest part of the head, 2 cm above the eyebrows and ears.',
    howToMeasure: [
      'Wrap tape around the head, positioning it 2 cm (about 1 inch) above the eyebrows in front.',
      'Pass tape over the slight bump at the back of the head (occipital bone).',
      'Keep tape level and snug without tension.',
    ],
    proTip: 'Used for hats, berets, head wraps, caps, and hoods.',
    commonMistake: 'Placing the tape too high across the crown of the head.',
    minCm: 35,
    maxCm: 70,
    minInches: 14,
    maxInches: 27.5,
    silhouetteRegion: 'head',
    indicatorY: 10,
    indicatorType: 'circumference',
  },
];

export const getMeasurementGuideByKey = (key: string): MeasurementGuideItem | undefined => {
  const normalized = key.toUpperCase().trim();
  return MEASUREMENT_GUIDES.find((item) => item.key === normalized);
};
