export {
  DESIGN_FIT_PREFERENCE_OPTIONS,
  DESIGN_MAX_MEDIA_COUNT,
  DESIGN_MEDIA_OPTIONAL_SLOTS,
  DESIGN_MEDIA_REQUIRED_SLOTS,
  DESIGN_MEDIA_SLOTS,
  DESIGN_REQUIRED_MEDIA_COUNT,
  DESIGN_TARGET_AGE_OPTIONS,
  type DesignFitPreference,
  type DesignTargetAgeGroup,
} from '@/constants/designCreation';
